import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';

import { cn } from '@/utils';
import { Inter, Roboto_Mono } from 'next/font/google';

import './globals.css';

const mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: 'variable',
});
const sans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: 'variable',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          mono.variable,
          sans.variable,
          'bg-orange-50 font-sans text-orange-950 motion-safe:scroll-smooth dark:bg-orange-950 dark:text-orange-50',
        )}
      >
        {children}
      </body>
    </html>
  );
}
